repos:

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        exclude: 'migrations/'
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: isort
        exclude: 'migrations/'
        language: system
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8
        exclude: 'migrations/'
        language: system
        types: [python]