[tool.isort]
skip = [
    "migrations/",
    ".git",
    ".pytest_cache",
    "__pycache__,",
    ".venv",
    "env",
    "venv",
]
profile = "black"
multi_line_output = "3"
include_trailing_comma = "True"
force_grid_wrap = "0"
use_parentheses = "True"

[tool.black]
line-length = "110"
multi_line_output = "3"
include = '\.pyi?$'
exclude = '''
/(
    migrations
    | .git
    | .pytest_cache
    | __pycache__,
    | .venv
    | env
    | venv
    | migrations
)/
'''